# shamefullyHoist is crucial for imports
shamefullyHoist: true
minimumReleaseAge: 10080
blockExoticSubdeps: true
strictDepBuilds: true
packages:
    - 'apps/*'
allowBuilds:
    esbuild: true
    sharp: true
    '@swc/core': true
